project:
  type: website
  output-dir: docs
  
website:
  title: "MathInsights"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: dataclean.qmd
        text: Data Cleaning

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

